networks:
  internal:
    driver: bridge

volumes:
  media_volume:
  static_volume:
  sqlite_volume:

services:
  backend:
    container_name: backend
    mem_limit: 1g
    cpus: 0.5

    build:
      context: ../../
      dockerfile: Dockerfile
    volumes:
      - media_volume:/app/media
      - static_volume:/app/static
      - sqlite_volume:/app/db
    ports:
      - "8000:8000"
    networks:
      - internal
    restart: unless-stopped

  nginx:
    image: nginx:latest
    mem_limit: 1g
    cpus: 0.5

    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - media_volume:/app/media
      - static_volume:/app/static
      - ../../index.html:/usr/share/nginx/html/index.html:ro
    depends_on:
      - backend
    ports:
      - "80:80"
    networks:
      - internal
    restart: unless-stopped
