networks:
  internal:
    driver: bridge

volumes:
  media_volume:
  static_volume:
  sqlite_volume:

services:
  backend:
    container_name: backend
    build:
      context: ../../
      dockerfile: Dockerfile
    volumes:
      - media_volume:/app/media
      - static_volume:/app/static
      - sqlite_volume:/app/db
    expose:
      - 8000

    networks:
      - internal

  nginx:
    image: nginx:latest
    networks:
      - internal
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - media_volume:/app/media
      - static_volume:/app/static
      - ../../index.html:/usr/share/nginx/html/index.html:ro
    depends_on:
      - backend
    ports:
      - "80:80"

