# Generated by Django 5.2.6 on 2025-09-21 12:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stars', models.IntegerField()),
                ('comment', models.TextField(blank=True, default='')),
                ('sent_to_store', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taken_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(blank=True, max_length=160)),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/meals/')),
                ('calories', models.IntegerField(default=0)),
                ('protein_g', models.IntegerField(default=0)),
                ('fat_g', models.IntegerField(default=0)),
                ('carbs_g', models.IntegerField(default=0)),
                ('servings', models.FloatField(default=1.0)),
                ('ingredients', models.JSONField(blank=True, default=list)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meals', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NutritionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calories', models.IntegerField(default=0)),
                ('protein_g', models.IntegerField(default=0)),
                ('fat_g', models.IntegerField(default=0)),
                ('carbs_g', models.IntegerField(default=0)),
                ('generated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='plan', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], default='other', max_length=16)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('units', models.CharField(choices=[('metric', 'Metric'), ('imperial', 'Imperial')], default='metric', max_length=16)),
                ('height_cm', models.FloatField(blank=True, null=True)),
                ('weight_kg', models.FloatField(blank=True, null=True)),
                ('activity', models.CharField(choices=[('sedentary', 'Sedentary'), ('normal', 'Normal'), ('active', 'Active')], default='normal', max_length=16)),
                ('goal', models.CharField(choices=[('lose', 'Lose weight'), ('maintain', 'Maintain'), ('gain', 'Gain weight')], default='maintain', max_length=16)),
                ('desired_weight_kg', models.FloatField(blank=True, null=True)),
                ('allergies', models.TextField(blank=True, default='')),
                ('has_premium', models.BooleanField(default=False)),
                ('trial_ends_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
