# Generated by Django 5.2.6 on 2025-09-27 08:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='pendingsignup',
            name='api_pending_email_33d466_idx',
        ),
        migrations.RemoveIndex(
            model_name='pendingsignup',
            name='api_pending_expires_7315b3_idx',
        ),
        migrations.AlterField(
            model_name='pendingsignup',
            name='attempts',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='pendingsignup',
            name='email',
            field=models.EmailField(db_index=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='pendingsignup',
            name='otp_salt',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='pendingsignup',
            name='otp_sent_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='pendingsignup',
            name='resends',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
