# Generated by Django 5.2.6 on 2025-09-22 10:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_pendingsignup'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pendingsignup',
            options={'verbose_name': 'Pending signup session', 'verbose_name_plural': 'Pending signup sessions'},
        ),
        migrations.RemoveField(
            model_name='pendingsignup',
            name='is_verified',
        ),
        migrations.RemoveField(
            model_name='pendingsignup',
            name='otp_code',
        ),
        migrations.RemoveField(
            model_name='pendingsignup',
            name='password',
        ),
        migrations.AddField(
            model_name='pendingsignup',
            name='attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pendingsignup',
            name='otp_hash',
            field=models.CharField(default=0, max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pendingsignup',
            name='otp_salt',
            field=models.CharField(default=0, max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pendingsignup',
            name='otp_sent_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='pendingsignup',
            name='password_sha256',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='pendingsignup',
            name='resends',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pendingsignup',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='pendingsignup',
            name='locale',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='pendingsignup',
            name='username',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddIndex(
            model_name='pendingsignup',
            index=models.Index(fields=['email'], name='api_pending_email_33d466_idx'),
        ),
        migrations.AddIndex(
            model_name='pendingsignup',
            index=models.Index(fields=['session_id'], name='api_pending_session_7bc911_idx'),
        ),
        migrations.AddIndex(
            model_name='pendingsignup',
            index=models.Index(fields=['expires_at'], name='api_pending_expires_7315b3_idx'),
        ),
    ]
