# Generated by Django 5.2.6 on 2025-09-23 20:51

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_pendingsignup_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pendingsignup',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='pendingsignup',
            name='api_pending_email_33d466_idx',
        ),
        migrations.RemoveIndex(
            model_name='pendingsignup',
            name='api_pending_session_7bc911_idx',
        ),
        migrations.RemoveIndex(
            model_name='pendingsignup',
            name='api_pending_expires_7315b3_idx',
        ),
        migrations.RemoveField(
            model_name='pendingsignup',
            name='id',
        ),
        migrations.RemoveField(
            model_name='pendingsignup',
            name='otp_sent_at',
        ),
        migrations.RemoveField(
            model_name='pendingsignup',
            name='resends',
        ),
        migrations.RemoveField(
            model_name='pendingsignup',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='pendingsignup',
            name='username',
        ),
        migrations.AlterField(
            model_name='pendingsignup',
            name='email',
            field=models.EmailField(db_index=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='pendingsignup',
            name='locale',
            field=models.CharField(default='ru', max_length=8),
        ),
        migrations.AlterField(
            model_name='pendingsignup',
            name='otp_hash',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='pendingsignup',
            name='password_sha256',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='pendingsignup',
            name='session_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
