# Generated by Django 5.2.6 on 2025-09-29 11:56

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_entitlement_paymentreceiptios'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('phone_number', models.CharField(max_length=32, validators=[django.core.validators.RegexValidator('^\\+?\\d{7,15}$', message='Phone must be in international format, e.g. +996XXXXXXXXX')])),
                ('comment', models.TextField(blank=True, default='')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='uploads/reports/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
