# Generated by Django 5.2.6 on 2025-09-23 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_pendingsignup_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingsignup',
            name='otp_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pendingsignup',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='pendingsignup',
            name='username',
            field=models.CharField(default=0, max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pendingsignup',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='pendingsignup',
            name='otp_salt',
            field=models.CharField(max_length=16),
        ),
        migrations.AddIndex(
            model_name='pendingsignup',
            index=models.Index(fields=['email'], name='api_pending_email_33d466_idx'),
        ),
        migrations.AddIndex(
            model_name='pendingsignup',
            index=models.Index(fields=['expires_at'], name='api_pending_expires_7315b3_idx'),
        ),
    ]
