# Generated by Django 5.2.6 on 2025-09-24 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_pendingsignup_otp_sent_at_pendingsignup_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingsignup',
            name='resends',
            field=models.IntegerField(default=0),
        ),
    ]
